#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Mon Apr 24 11:24:05 2017

import wx

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, _("Spam Detector"), style=wx.ALIGN_CENTRE)
        self.label_2 = wx.StaticText(self, -1, _("Filename"))
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.label_3 = wx.StaticText(self, -1, _("Click the button below to check whether the given file is spam or not\n"))
        self.button_1 = wx.Button(self, -1, _("CHECK"))
        self.button_2 = wx.Button(self, -1, "")
        self.label_4 = wx.StaticText(self, -1, _("File contents"), style=wx.ALIGN_CENTRE)
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "")
        self.button_3 = wx.Button(self, -1, _("EXIT"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.check, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.ext, self.button_3)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.label_1.SetBackgroundColour(wx.Colour(50, 153, 204))
        self.label_1.SetForegroundColour(wx.Colour(35, 35, 142))
        self.label_1.SetFont(wx.Font(40, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_2.SetForegroundColour(wx.Colour(35, 35, 142))
        self.label_2.SetFont(wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_ctrl_1.SetMinSize((200, 40))
        self.text_ctrl_1.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_3.SetFont(wx.Font(20, wx.MODERN, wx.ITALIC, wx.NORMAL, 0, ""))
        self.button_1.SetMinSize((190, 70))
        self.button_1.SetBackgroundColour(wx.Colour(26, 26, 106))
        self.button_1.SetForegroundColour(wx.Colour(0, 127, 255))
        self.button_1.SetFont(wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_2.SetMinSize((149, 58))
        self.button_2.SetBackgroundColour(wx.Colour(176, 0, 255))
        self.button_2.SetForegroundColour(wx.Colour(255, 255, 255))
        self.button_2.SetFont(wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_4.SetMinSize((150, 75))
        self.label_4.SetForegroundColour(wx.Colour(47, 11, 192))
        self.label_4.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Cantarell"))
        self.text_ctrl_2.SetMinSize((690, 100))
        self.text_ctrl_2.SetBackgroundColour(wx.Colour(223, 223, 223))
        self.button_3.SetMinSize((150, 60))
        self.button_3.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.button_3.SetForegroundColour(wx.Colour(255, 239, 248))
        self.button_3.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Cantarell"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(self.label_1, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(grid_sizer_1, 1, 0, 0)
        sizer_1.Add(self.label_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.button_2, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.label_4, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.text_ctrl_2, 0, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.button_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def check(self, event):  # wxGlade: MyFrame.<event_handler>
        #print "Event handler `check' not implemented!"
        grad=0.512058826033 #Our gradient value as calculated with the help of logistic regression
        name=self.text_ctrl_1.Value
	try:
		f=open(name,"r")
	except IOError as e:
		self.button_2.SetLabel("No such file")
		self.text_ctrl_2.SetValue("File does not exist")
	g=open("nocspamw.txt","r")
	fcontent=f.read();
	gcontent=g.read();
	fwords=fcontent.split()
	gwords=gcontent.split()
	twc=0.0
	swc=0.0
	for i in fwords:
		twc=twc+1
	for i in fwords:
		for j in gwords:
			if i==j:
				swc=swc+1
	prob=float(swc/twc)
	#print "Total word count= ",twc
	#print "Spam word count= ",swc
	#print "Probability obtained= ",prob
	if prob>grad:
		self.button_2.SetLabel("Spam")
	else:
		self.button_2.SetLabel("Not Spam")
	self.text_ctrl_2.SetValue(fcontent)


	event.Skip()

    def ext(self, event):  # wxGlade: MyFrame.<event_handler>
        #print "Event handler `ext' not implemented!"
	exit()        
	event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    import gettext
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
